config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  
  get 'member/:id', to: 'members#show', as: 'member' #assigns a name to the route for convenience
  get 'edit_description', to: 'members#edit_description', as: 'edit_member_description'
  patch 'update_description', to: 'members#update_description', as: 'update_member_description'

  get 'edit_personal_details', to: 'members#edit_personal_details', as: 'edit_member_personal_details'
  patch 'update_dpersonal_details', to: 'members#update_personal_details', as: 'update_member_personal_details'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  PROFILE_TITLE = [
    'Senior ROR developer',
    'Full Stack ROR developer',
    'Senior Full Stack ROR developer',
    'Junior Full Stack ROR developer',
    'Senior JAVA developer',
    'Senior Front End developer'
  ].freeze #use freeze method so that it can not be added(edited) dynamically

  def name
    "#{first_name} #{last_name}".strip #this strip method will remove all the blank spaces from left and right. 
  end

  def address
    "#{city}, #{state}, #{country}, #{pincode}"
  end

  def self.ransackable_attributes(auth_object = nil)
    ['country', 'city']
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #@users = User.all
    #@users = User.limit(16).order(:created_at)
    @q = User.ransack(params[:q])
    @users = @q.result.limit(16).order(:created_at)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    before_action :authenticate_user!, only: %i[edit_description update_description edit_personal_details update_personal_details]

    def show
        @user = User.find(params[:id])
    end

    def edit_description
        #@user = User.find(params[:id])
    end

    def update_description
        #@user = User.find(params[:id])
        respond_to do |format|
            if current_user.update(about: params[:user][:about])
                format.turbo_stream { render turbo_stream: turbo_stream.replace('member-description', partial: 'members/member_description', locals: { user: current_user }) }
            end
        end
    end

    def edit_personal_details

    end

    def update_personal_details
        respond_to do |format|
            if current_user.update(user_personal_info_params)
                format.turbo_stream { render turbo_stream: turbo_stream.replace('member-personal-details', partial: 'members/member_personal_details', locals: { user: current_user }) }
            end
        end
    end

    private

    def user_personal_info_params
        params.require(:user).permit(:first_name, :last_name, :city, :state, :country, :pincode, :profile_title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="col-lg-10 mx-auto mt-5">

    <div class="card mt-4 mb-4">
        <div class="card-body">
            <h3 class="text-center mb-3">Search professionals across the world!</h3>
            <%= search_form_for @q, url: root_path do |form| %>
                <div class="input-group mb-3">
                    <%= form.search_field :city_or_country_cont, class: "form-control", placeholder: "Search by country or city", area: { label: "Search by country or city", describedby: "button-addon2" } %>
                    <%= form.submit "Search", class: "btn btn-primary", id: "button-addon2" %>
                </div>
            <% end %>
        </div>
    </div>

    <div class="row mt-4 mb-4">
        <% @users.each do |user| %>
            <div class="col-lg-3 mb-3 mt-3">
                <div class="card text-center shadow" style="min-height: 400px;">
                    <div class="card-body">
                        <%= image_tag "avatar.jpg", style: "width: 150px; border-radius: 50%; border: 2px solid #0d6efd;", class: 'mb-3' %>
                        <div class="user-info" data-controller="user-name">
                            <h5 data-user-name-target="name" data-action="click->user-name#getUserName"><%= user.name %></h5>
                            <p class="lead"><%= user.profile_title %></p>
                            <small class="text-primary"><%= user.country %></small><br>

                            <%= link_to "View Profile", member_path(user), class: "btn btn-primary mt-3" %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevCommunity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-lg-10 mx-auto">
          <%= render "shared/header" %>
        </div>
        <%= yield %>
        <%= turbo_frame_tag 'remote_modal' %>
        <div class="col-lg-10 mx-auto">
          <%= render "shared/footer" %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/members/_description_modal.html.erb
<%= form_with model: current_user, url: update_member_description_path, method: :patch do |form| %>
    <div class="modal-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <label class="mb-3">Edit your description here. Try to keep it simple and to the point so the others can find valuable details of yours.</label>
                    <%= form.text_area :about, value: current_user.about, class: "form-control", rows: 15 %>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <%= form.submit 'Save Changes', class: "btn btn-primary", data: { action: 'click->bs-modal#submitEnd' } %>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    </div>
<% end %>

app/views/members/_member_description.html.erb
<p class="lead" id="member-description"><%= user.about %></p>

app/views/members/_member_personal_details.html.erb
<div class="card mb-5" id="member-personal-details">
    <div class="row">
        <div class="col-lg-4">
            <%=image_tag "avatar.jpg", class: "img-fluid" %>
        </div>
        <div class="col-lg-8">
            <div class="card-body">
                <h3 class="fw-bold"><%= user.name %></h3>
                <p class="lead"><%= user.profile_title %></p>
                <p class="lead text-primary"><%= user.address %></p>

                <% if user_signed_in? && user == current_user %>
                    <div class="col-lg-6">
                        <div class="d-flex justify-content-end">
                            <%= link_to edit_member_personal_details_path, data: { controller: "edit-user-details" } do %>
                                <i class="bi bi-pencil-fill"></i>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>    

app/views/members/_personal_info_modal.html.erb
<%= form_with model: current_user, url: update_member_personal_details_path, method: :patch do |form| %>
    <div class="modal-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group row">
                    <div class="col-lg-6">
                        <%= form.label :first_name, class: "mb-3 mt-3" %>
                        <%= form.text_field :first_name, class: "form-control", value: current_user.first_name %>
                    </div>
                    <div class="col-lg-6">
                        <%= form.label :last_name, class: "mb-3 mt-3" %>
                        <%= form.text_field :last_name, class: "form-control", value: current_user.last_name %>
                    </div>
                </div>
            </div>

            <div class="col-lg-12">
                <div class="form-group row">
                    <div class="col-lg-6">
                        <%= form.label :city, class: "mb-3 mt-3" %>
                        <%= form.text_field :city, class: "form-control", value: current_user.city %>
                    </div>
                    <div class="col-lg-6">
                        <%= form.label :state, class: "mb-3 mt-3" %>
                        <%= form.text_field :state, class: "form-control", value: current_user.state %>
                    </div>
                    <div class="col-lg-6">
                        <%= form.label :country, class: "mb-3 mt-3" %>
                        <%= form.text_field :country, class: "form-control", value: current_user.country %>
                    </div>
                    <div class="col-lg-6">
                        <%= form.label :pincode, class: "mb-3 mt-3" %>
                        <%= form.text_field :pincode, class: "form-control", value: current_user.pincode %>
                    </div>
                </div>
            </div>

            <div class="col-lg-12">
                <div class="form-group">
                    <%= form.label :profile_title, class: "mb-3 mt-3" %>
                    <%= form.text_field :profile_title, class: "form-control", value: current_user.profile_title %>
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <%= form.submit 'Save Changes', class: "btn btn-primary", data: { action: 'click->bs-modal#submitEnd' } %>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    </div>
<% end %>

app/views/members/edit_description.turbo_stream.erb
<%= turbo_stream.replace 'remote_modal' do %>
    <%= render 'shared/turbo_modal', modal_title: 'Edit your description', form_partial: 'members/description_modal' %>
<% end %>

app/views/members/edit_personal_details.turbo_stream.erb
<%= turbo_stream.replace 'remote_modal' do %>
    <%= render 'shared/turbo_modal', modal_title: 'Edit your personal details', form_partial: 'members/personal_info_modal' %>
<% end %>

app/views/members/show.html.erb
<div class="col-lg-10 mx-auto mt-5">
    <%= render 'member_personal_details', user: @user %>

    <div class="card mb-5">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="d-flex justify-content-start">
                        <h3>About</h3>
                    </div>
                </div>
                <% if user_signed_in? && @user == current_user %>
                    <div class="col-lg-6">
                        <div class="d-flex justify-content-end">
                            <%= link_to edit_member_description_path, data: { controller: "edit-user-description" } do %>
                                <i class="bi bi-pencil-fill"></i>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>

            <%= render 'member_description', user: @user %>
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer class="pd-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-lg-4 col-md">
            <small class="d-block mb-3 text-muted">Company@ 2022-2023</small>
        </div>
        <div class="col-lg-4">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1">
                    <a class="link-secondary text-decoration-none" href="javascript:void(0)">About Us</a>
                </li>
                <li class="mb-1">
                    <a class="link-secondary text-decoration-none" href="javascript:void(0)">Contact Us</a>
                </li>
                <li class="mb-1">
                    <a class="link-secondary text-decoration-none" href="javascript:void(0)">Our Mission</a>
                </li>
            </ul>
        </div>
        <div class="col-lg-4">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1">
                    <a class="link-secondary text-decoration-none" href="javascript:void(0)">Blogs</a>
                </li>
                <li class="mb-1">
                    <a class="link-secondary text-decoration-none" href="javascript:void(0)">Careers</a>
                </li>
                <li class="mb-1">
                    <a class="link-secondary text-decoration-none" href="javascript:void(0)">Profiles</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to "Dev Community", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My Profile", member_path(current_user), class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure to Sign Out?" }, class: "nav-link active" %>
          </li>
        <% else%>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link active" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_turbo_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
    <div class="modal fade" id="bsTurboModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-controller="bs-modal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel"><%= modal_title %></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <%= render form_partial %>
            </div>
        </div>
    </div>
<% end %>